create table tag (
    id bigint generated by default as identity (start with 1), 
    name varchar(255) not null, 
    description varchar(255), 
    created_on timestamp not null, 
    updated_on timestamp not null, 
    version integer, 
    primary key (id)
);
alter table tag add constraint uk_tag_name unique (name)

create table thing (
    id bigint generated by default as identity (start with 1), 
    name varchar(255) not null, 
    description varchar(255), 
    created_on timestamp not null, 
    updated_on timestamp not null, 
    version integer, 
    primary key (id)
);
alter table thing add constraint uk_thing_name unique (name)

create table thing_tags (
    thing bigint not null, 
    tags bigint not null
);
alter table thing_tags add constraint fk_thing_tags_tag foreign key (tags) references tag;
alter table thing_tags add constraint fk_thing_tags_thing foreign key (thing) references thing;